Document: ecoin-qt
Title: Debian ecoin-qt Manual
Author: <insert document author here>
Abstract: This manual describes what ecoin-qt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ecoin-qt/ecoin-qt.sgml.gz

Format: postscript
Files: /usr/share/doc/ecoin-qt/ecoin-qt.ps.gz

Format: text
Files: /usr/share/doc/ecoin-qt/ecoin-qt.text.gz

Format: HTML
Index: /usr/share/doc/ecoin-qt/html/index.html
Files: /usr/share/doc/ecoin-qt/html/*.html
